CREATE DATABASE students;
USE students;

CREATE TABLE name (
FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR(50)
);

INSERT INTO name
(FIRST_NAME, LAST_NAME)
VALUES
("Aryan", "Singh"),
("Rahul", "Kumar");

SELECT UPPER(FIRST_NAME) FROM name;
SELECT LENGTH(FIRST_NAME) FROM name;
SELECT SUBSTRING(FIRST_NAME, 1, 3), FIRST_NAME FROM name;
SELECT CONCAT(FIRST_NAME, LAST_NAME), FIRST_NAME, LAST_NAME FROM name;
SELECT REPLACE(FIRST_NAME, "Rahul", "Sahil"), FIRST_NAME, LAST_NAME FROM name;
 