CREATE DATABASE school;
USE school;

CREATE TABLE course (
DEPT_ID INT PRIMARY KEY,
NAME VARCHAR(50)
);

INSERT INTO course
(DEPT_ID, NAME)
VALUES
(101, "SCIENCE"),
(102, "ENGLISH"),
(103, "HINDI");

#Cascading for foreign key

CREATE TABLE teacher (
ID INT PRIMARY KEY,
NAME VARCHAR(50),
DEPT_ID INT,
FOREIGN KEY (DEPT_ID)REFERENCES course(DEPT_ID)
ON DELETE CASCADE
ON UPDATE CASCADE
);

INSERT INTO teacher
(ID, NAME, DEPT_ID)
VALUES 
(101, "ADAM", 101),
(102, "BOB", 102),
(103, "CASEY", 102),
(104, "DONALD", 103);

UPDATE COURSE
SET DEPT_ID = 107
WHERE DEPT_ID = 102;

SELECT * FROM teacher;